services:
  rabbitmq:
    build:
      context: ./rabbitmq-custom
    ports:
      - "5552:5552"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_stream advertised_host rabbitmq -rabbit loopback_users "none"'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - game-net

  gameoflife:
    build: gameoflife/.
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
    networks:
      - game-net

networks:
  game-net:
    driver: bridge

volumes:
  rabbitmq_data:
